### PR TITLE
Throw errors when importing objects with duplicate primary keys

### LINKED ISSUE #192: Throw exception when creating objects with duplicate primary keys
Current C-API is returning any existing object when calling `realm_object_create_with_primary` if an object with the given primary key already exists. This means that the current behavior of our `create`/`copyToRealm` is actually an `copyOrUpdate`. 

This could be fixed by checking for existence of the object prior to creating it and throwing the error ourselves, but requested this to be part of the C-API as it probably also would be useful for other SDKs and error reporting would be more uniform if all constraint violations of the same constraint are raised the same way. 

C-API issue is in https://github.com/realm/realm-core/issues/4595

### PR DESCRIPTION
**Pull request by rorbech**
This is adding a manual check for conflicting primary keys before adding new objects. 

Closes #192

### CODE REVIEW

File: packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt [hunk 1]
```diff
@@ -17,11 +17,15 @@
...
 
 import kotlinx.coroutines.CoroutineDispatcher
+import kotlin.jvm.JvmInline
 
 // FIXME API-INTERNAL Consider adding marker interfaces NativeRealm, NativeRealmConfig, etc. as type parameter
 //  to NativePointer. NOTE Verify that it is supported for Kotlin Native!
 
-inline class ColumnKey(val key: Long)
+@JvmInline
+value class ClassKey(val key: Long)
```
Comment (cmelchior) [inline packages/cinterop/src/commonMain/kotlin/io/realm/interop/RealmInterop.kt:26]: Perhaps add docs for what they represent?

**Review by cmelchior — APPROVED** [review]
Good work-around until we get support from the C-API. Only needs an CHANGELOG update as well 👍

**Review by nhachicha — APPROVED** [review]
Nice 👍
