### PR TITLE
Fix missing scheduler on Linux and Windows (JVM)

### LINKED ISSUE #1502: Missing scheduler on platforms
On our latest release I am seeing some weird behavior on Github Actions:

```
Starting process 'Gradle Test Executor 1'. Working directory: /home/runner/work/realm-kotlin/realm-kotlin/packages/test-base Command: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.20-8/x64/bin/java -Dorg.gradle.internal.worker.tmpdir=/home/runner/work/realm-kotlin/realm-kotlin/packages/test-base/build/tmp/jvmTest/work -Dorg.gradle.native=false @/home/runner/.gradle/.tmp/gradle-worker-classpath412522939317337655txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'
/work/packages/external/core/src/realm/object-store/util/scheduler.cpp:133: [realm-core-13.19.0] No built-in scheduler implementation for this platform. Register your own with Scheduler::set_default_factory()
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0xac046b) [0x7fc0db6bc46b]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0xac06da) [0x7fc0db6bc6da]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0xac05a0) [0x7fc0db6bc5a0]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x54fd17) [0x7fc0db14bd17]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x552a49) [0x7fc0db14ea49]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x55160a) [0x7fc0db14d60a]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x54fcd5) [0x7fc0db14bcd5]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x3b7ae3) [0x7fc0dafb3ae3]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(+0x3b7ee0) [0x7fc0dafb3ee0]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(realm_scheduler_make_default+0x14) [0x7fc0dafb3b47]
/home/runner/.cache/io.realm.kotlin/cabe917019091876f1f961bcf664d49d26519d7f/librealmc.so(Java_io_realm_kotlin_internal_interop_realmcJNI_realm_1scheduler_1make_1default+0x25) [0x7fc0daf4b8fd]
[0x7fc11876b930]
!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
Thread name: Test worker @co
```

it looks like the default scheduler is missing on Ubuntu.

A similar issue was reported in Core for Windows: https://github.com/realm/realm-core/issues/6951

### PR DESCRIPTION
**Pull request by cmelchior**
Closes #1502 

This PR aligns the behavior of schedulers across all platforms. Previously Darwin was using their custom run-loop, which was why it worked there while Linux and Windows failed.

The fix has been verified on Github Actions: https://github.com/realm/realm-kotlin/actions/runs/6098168339

### CODE REVIEW

File: packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp [hunk 1]
```diff
@@ -1048,3 +1048,8 @@ realm_sync_thread_error(realm_userdata_t userdata, const char* error) {
     env->CallVoidMethod(static_cast<jobject>(userdata), java_callback_method, to_jstring(env, msg));
     jni_check_exception(env);
 }
+
+realm_scheduler_t*
+realm_create_generic_scheduler() {
+    return new realm_scheduler_t{realm::util::Scheduler::make_generic()};
```
Comment (rorbech) [inline packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:1054]: Hmm. Seems weird that the C-API offers an API around default schedulers that aren't necessarily support and does not have a API for this.

**Review by rorbech — APPROVED** [review]
Don't want to block the release, but it seems to me that the scheduler C-API should be reworked to enable us to generate the generic scheduler and not the default that could fail. Maybe file an issue for that.  

Assuming that you actually verified this on the GHA branch?

File: packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp (hunk 1 above)
Comment (cmelchior) [reply packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:1054]: Agree, it feels weird. I'll file an issue in Core for it

**Review by clementetb — APPROVED** [review]
Happy once CI is happy.

File: packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp (hunk 1 above)
Comment (nhachicha) [inline packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:1054]: formatting

Comment (cmelchior) [reply packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:1054]: But that one doesn't do anything, correct? Which seems to make it dangerous to use unless specifically requested?

Comment (nhachicha) [reply packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:1054]: That's the goal, the generic one also don't do anything. They are mainly used for use case where we want to open a Realm without notifications  (like the Frozen Realms or when doing a compact). The dummy scheduler's implementation is slightly simpler that's all (both don't deliver anything)
