### PR TITLE
Fix error formatting for log entries without arguments

### LINKED ISSUE #1034: Crash when logging messages with formatting specifiers
If messages passed to the logger contains formatting specifiers it will cause the app to crash with a trace similar to the below:
```
java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI NewString called with pending exception java.util.MissingFormatArgumentException: 
                                                                                                    java_vm_ext.cc:579]   at java.util.Formatter java.util.Formatter.format(java.util.Locale, java.lang.String, java.lang.Object[]) (Formatter.java:2523)
                                                                                                    java_vm_ext.cc:579]   at java.util.Formatter java.util.Formatter.format(java.lang.String, java.lang.Object[]) (Formatter.java:2459)
                                                                                                    java_vm_ext.cc:579]   at java.lang.String java.lang.String.format(java.util.Locale, java.lang.String, java.lang.Object[]) (String.java:2911)
                                                                                                    java_vm_ext.cc:579]   at java.lang.String io.realm.kotlin.internal.platform.LogCatLogger.formatMessage(java.lang.String, java.lang.Object[]) (LogCatLogger.kt:95)
                                                                                                    java_vm_ext.cc:579]   at java.lang.String io.realm.kotlin.internal.platform.LogCatLogger.prepareLogMessage(java.lang.Throwable, java.lang.String, java.lang.Object[]) (LogCatLogger.kt:85)
                                                                                                    java_vm_ext.cc:579]   at void io.realm.kotlin.internal.platform.LogCatLogger.log(io.realm.kotlin.log.LogLevel, java.lang.Throwable, java.lang.String, java.lang.Object[]) (LogCatLogger.kt:38)
                                                                                                    java_vm_ext.cc:579]   at void io.realm.kotlin.log.RealmLogger$DefaultImpls.log(io.realm.kotlin.log.RealmLogger, io.realm.kotlin.log.LogLevel, java.lang.String) (RealmLogger.kt:47)
                                                                                                    java_vm_ext.cc:579]   at void io.realm.kotlin.internal.platform.LogCatLogger.log(io.realm.kotlin.log.LogLevel, java.lang.String) (LogCatLogger.kt:31)
                                                                                                    java_vm_ext.cc:579]   at void io.realm.kotlin.mongodb.internal.AppConfigurationImpl$initializeSyncClientConfig$1$1.log(short, java.lang.String) (AppConfigurationImpl.kt:93)
                                                                                                    java_vm_ext.cc:579] 
                                                                                                    java_vm_ext.cc:579]     in call to NewString
```

### PR DESCRIPTION
**Pull request by rorbech**
When messages was logged with formatting arguments, it was erroneously passed a `null` argument, which triggered formatting even though it should. 

Closes #1034

### CODE REVIEW

File: packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp [hunk 1]
```diff
@@ -533,6 +533,7 @@ void set_log_callback(realm_sync_client_config_t* sync_client_config, jobject lo
                                                                                "log",
                                                                                "(SLjava/lang/String;)V");
                                                   jenv->CallVoidMethod(log_callback, log_method, level, to_jstring(jenv, message));
+                                                  jni_check_exception(jenv);
```
Comment (cmelchior) [inline packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:536]: Could we write a test that checks this?

Comment (rorbech) [reply packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:536]: I think it is quite hard to write some tests that verifies that the logger writes the correct thing, but I guess we could write some tests just to ensure that we do not crash for string containing formatting specifiers, etc. But could consider to do this in another PR.

Comment (cmelchior) [reply packages/jni-swig-stub/src/main/jni/realm_api_helpers.cpp:536]: I would vote for just merging this, since it is blocking other things and create an issue for tests for this.

**Review by cmelchior — APPROVED** [review]
