### PR TITLE
Fix Realm.asFlow() potentially missing an update when doing a write immediately after opening the Realm

### LINKED ISSUE #1582: Flaky test: io.realm.kotlin.test.common.VersionTrackingTests.initialVersionDereferencedAfterFirstWrite
On Github Actions: https://github.com/realm/realm-kotlin/runs/19051481379

```
kotlinx.coroutines.TimeoutCancellationException: Timeout: null
at io.realm.kotlin.test.util.UtilsKt$receiveOrFail$2$2.invokeSuspend(Utils.kt:102)
at io.realm.kotlin.test.util.UtilsKt$receiveOrFail$2$2.invoke(Unknown Source:8)
at io.realm.kotlin.test.util.UtilsKt$receiveOrFail$2$2.invoke(Unknown Source:2)
at kotlinx.coroutines.selects.SelectImplementation$ClauseData.invokeBlock(Select.kt:818)
at kotlinx.coroutines.selects.SelectImplementation.complete(Select.kt:692)
at kotlinx.coroutines.selects.SelectImplementation.doSelectSuspend(Select.kt:434)
at kotlinx.coroutines.selects.SelectImplementation.access$doSelectSuspend(Select.kt:243)
at kotlinx.coroutines.selects.SelectImplementation$doSelectSuspend$1.invokeSuspend(Unknown Source:14)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at io.realm.kotlin.test.common.VersionTrackingTests.initialVersionDereferencedAfterFirstWrite(VersionTrackingTests.kt:227)
```

I wonder if our Scheduler changes have somehow exposed race conditions that was hidden before 🤔

### PR DESCRIPTION
**Pull request by cmelchior**
Closes #1582
Closes https://github.com/realm/realm-kotlin/issues/1574

### CODE REVIEW

**Comment by cmelchior** [comment]
Ready for review

File: packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt [hunk 1]
```diff
@@ -90,6 +90,45 @@ class RealmNotificationsTests : FlowableTests {
         }
     }
 
+    @Test
+    fun registerTwoFlows() = runBlocking {
```
Comment (rorbech) [inline packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmNotificationsTests.kt:94]: This was covered in `cancelAsFlow`, but I guess it is nice with an explicit test.

**Review by rorbech — APPROVED** [review]
Nice catch 🧐
