### PR TITLE
Guard notifying outdated scheduler

### LINKED ISSUE #1543: Crash when notifying on released scheduler
CI android integration test is crashing once in a while in in `io.realm.kotlin.test.mongodb.common.SyncClientResetIntegrationTests.discardUnsyncedChanges_discards_attemptRecover_flx`. Stack trace from logcat is:
```
Cmdline: io.realm.sync.testapp
pid: 30615, tid: 2553, name: 520076934.realm  >>> io.realm.sync.testapp <<<
uid: 10090
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000059
Cause: null pointer dereference
    rax 0000000000000059  rbx 0000788c27007631  rcx 0000000000000000  rdx 0000788c21635d48
    r8  0000788f4e3ff440  r9  0000000000000020  r10 0000000000000002  r11 0000788c20fd5bb0
    r12 0000788c26999b80  r13 0000788c1f7e86b8  r14 0000788c8e960a80  r15 0000788c1f7e86b0
    rdi 84d88ed8ed1c6c7e  rsi 0000788c2163d200
    rbp 0000788c1f7e85c0  rsp 0000788c1f7e8530  rip 0000788c2162cd88
backtrace:
      #00 pc 00000000009a8d88  /data/app/~~vIgcHGNG4hXD6Pdfk1u4rw==/io.realm.sync.testapp-a_SlGK23QZoIIpnWSa7EOQ==/lib/x86_64/librealmc.so (BuildId: 931bf9bcb960735fbaaf3c2899fa81e4f72db77d)
      #01 pc 000000000037707e  /data/app/~~vIgcHGNG4hXD6Pdfk1u4rw==/io.realm.sync.testapp-a_SlGK23QZoIIpnWSa7EOQ==/lib/x86_64/librealmc.so (BuildId: 931bf9bcb960735fbaaf3c2899fa81e4f72db77d)
      #02 pc 000000000037d70b  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+219) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #03 pc 0000000000369459  /apex/com.android.art/lib64/libart.so (nterp_helper+2153) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #04 pc 00000000002d9b80  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~vIgcHGNG4hXD6Pdfk1u4rw==/io.realm.sync.testapp-a_SlGK23QZoIIpnWSa7EOQ==/base.apk!classes2.dex] (
c.invoke_core_notify_callback+0)
      #05 pc 0000000000368c28  /apex/com.android.art/lib64/libart.so (nterp_helper+56) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #06 pc 00000000002c7eb4  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~vIgcHGNG4hXD6Pdfk1u4rw==/io.realm.sync.testapp-a_SlGK23QZoIIpnWSa7EOQ==/base.apk!classes2.dex] (
heduler$notifyCore$1.invokeSuspend+44)
      #07 pc 0000000002135405  /memfd:jit-cache (deleted) (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+309)
      #08 pc 00000000020689c2  /memfd:jit-cache (deleted) (kotlinx.coroutines.DispatchedTask.run+2018)
      #09 pc 00000000020affc9  /memfd:jit-cache (deleted) (java.util.concurrent.ThreadPoolExecutor.runWorker+633)
      #10 pc 0000000000369aed  /apex/com.android.art/lib64/libart.so (nterp_helper+3837) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #11 pc 0000000000221334  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
      #12 pc 000000000036a7e5  /apex/com.android.art/lib64/libart.so (nterp_helper+7157) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #13 pc 00000000000f6740  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
      #14 pc 00000000003725c4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #15 pc 00000000003f21a6  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+214) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #16 pc 00000000007e617e  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, 
BuildId: 44bc52550248fc712a381bef164b75c7)
      #17 pc 000000000083a91c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1404) (BuildId: 44bc52550248fc712a381bef164b75c7)
      #18 pc 00000000000ccd2a  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+58) (BuildId: 007cb2313464df63debf8020e631c990)
      #19 pc 0000000000060d37  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55) (BuildId: 007cb2313464df63debf8020e631c990)
```
Seems to be when calling the notifier from our coroutine based scheduler. 

Observed twice on this PR https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1504/31/tests

### LINKED ISSUE #1558: Flaky test: realmAsFlow_doesNotTrackVersions[macos]
`
kotlin.AssertionError: VersionInfo(main=VersionData(current=null, active=[]), notifier=VersionData(current=VersionId(version=5), active=[]), writer=VersionData(current=VersionId(version=5), active=[])). Expected <1>, actual <0>.
`

From: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1510/12/tests

### LINKED ISSUE #1561: Flaky test: io.realm.kotlin.test.mongodb.common.SyncedRealmTests.mutableRealmInt_convergesAcrossClients
`io.realm.kotlin.test.mongodb.common.SyncedRealmTests.mutableRealmInt_convergesAcrossClients` occasionally fails with timeout:
```
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 60000 ms
at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
at java.lang.Thread.run(Thread.java:923)
```
Observed here among other places: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-1559/5/tests and https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/main/183/tests/

#1559 updates the CI BaaS to `2023-11-02` which have not yet shown the issue, so might just be incompatible versions. Locally built BaaS does not show it.

### PR DESCRIPTION
**Pull request by rorbech**
TODOs:
- [x] Await that core fix is merged https://github.com/realm/realm-core/pull/7102

Closes #1543
Closes #1558
Closes #1561

### CODE REVIEW

**Review by clementetb — COMMENTED** [review]
Awesome 💎.

I am unsure if that guard is enough to guarantee that the pointer has not been released when executing the job.

**Comment by clementetb** [comment]
Instead of guarding the `SingleThreadDispatcherScheduler`, we could cancel the coroutine scope just after closing the live Realm [here](https://github.com/realm/realm-kotlin/blob/65fa711fee39d2bbf27c3b3165e3307f77c06c98/packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt#L143).

Closing the coroutine there would cancel any pending works that were posted.

**Comment by rorbech** [comment]
> Instead of guarding the `SingleThreadDispatcherScheduler`, we could cancel the coroutine scope just after closing the live Realm [here](https://github.com/realm/realm-kotlin/blob/65fa711fee39d2bbf27c3b3165e3307f77c06c98/packages/library-base/src/commonMain/kotlin/io/realm/kotlin/internal/SuspendableNotifier.kt#L143).
> 
> Closing the coroutine there would cancel any pending core jobs that were posted.

If we have a user supplied scheduler then we cannot close it. There could also potentially be multiple scheduler in the same scope so feels better to use the exact signal from the user-data-free-callback to guard this.

**Comment by clementetb** [comment]
Yes, we shouldn't be closing the main `CoroutineContext` after releasing the dispatcher. 

The `if-guard` works, but depends on `AtomicBoolean` and requires to implement it on each platform. Coroutines have some structures to handle job cancelation gracefully. 

For example instead of working with the main `CoroutineContext` we could have a specific `CoroutineScope` associated to the scheduler to track all the jobs that have been posted via the scheduler. Once the scheduler is deleted, we can cancel the scope, and thus all pending jobs.

**Comment by rorbech** [comment]
But coroutine scopes are not preemptive so you are not guaranteed that any running coroutine will be immediately aborted. But you are right the current guard is actually not good enough ... though it looks like some of the schedulers in core uses a similar flag 🤔

**Review by nhachicha — APPROVED** [review]
Nice fix 👍 it looks like `io.realm.kotlin.test.darwin.CoroutineTests.dispatchBetweenThreads` is failing for macOS on CI

**Review by clementetb — APPROVED** [review]

File: packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt [hunk 1]
```diff
@@ -753,9 +753,10 @@ class SyncedRealmTests {
                         .mutableRealmIntField
                         .increment(1)
                 }
+                realm.syncSession.uploadAllLocalChanges(10.seconds)
```
Comment (cmelchior) [inline packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt:756]: Great catch 🙈, but any reason you are adding a timeout? The first upload doesn't have one

**Review by cmelchior — APPROVED** [review]
Awesome 💯

File: packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt (hunk 1 above)
Comment (rorbech) [reply packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt:756]: I added it because it would highlight what action is actually not executing as expected instead of just timeout out on the recipient side. I just added if for the uploads that I inserted, but just didn't walk over the rest of the code.

Comment (cmelchior) [reply packages/test-sync/src/commonTest/kotlin/io/realm/kotlin/test/mongodb/common/SyncedRealmTests.kt:756]: Ok 👍
