### PR TITLE
Apply Realm Kotlin compiler plugin after other plugins

### LINKED ISSUE #1251: RealmObject not serializable on Kotlin 1.8.0
When compiling the following class in an multiplatform library using Kotlin 1.8.0

```
import io.realm.kotlin.types.RealmObject
import io.realm.kotlin.types.annotations.Index
import io.realm.kotlin.types.annotations.PrimaryKey
import kotlinx.serialization.Serializable

@Serializable
class CityDto : RealmObject {
    @PrimaryKey
    var id: Long = Long.MIN_VALUE
    var cityOsmPolygonId: Long? = null
    var countyName: String = ""
    var cityName: String = ""
    var code: Int = Int.MIN_VALUE
    var longitude: Double = 0.0
    var latitude: Double = 0.0

    @Index
    var beneficiaryId: Long = 0
}
```

it fails with error: 
```
Details: kotlinx.serialization compiler plugin internal error: unable to transform declaration, see cause
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:184)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:46)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitClass(IrElementVisitorVoid.kt:111)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitClass(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:64)
	at org.jetbrains.kotlin.ir.declarations.IrFile.acceptChildren(IrFile.kt:36)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptChildrenVoid(IrVisitors.kt:15)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitElement(SerializationLoweringExtension.kt:42)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitPackageFragment(IrElementVisitorVoid.kt:190)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitPackageFragment(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:200)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitorVoid$DefaultImpls.visitFile(IrElementVisitorVoid.kt:198)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt$runOnFileInOrder$1.visitFile(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:30)
	at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtensionKt.runOnFileInOrder(SerializationLoweringExtension.kt:40)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationLoweringExtension.generate(SerializationLoweringExtension.kt:149)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:186)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:104)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:218)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:55)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:225)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Serializer for element of type io.realm.kotlin.internal.RealmObjectReference<com.example.realmbug.CityDto>? has not been found
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerSearchUtilKt.findTypeSerializerOrContext(SerializerSearchUtil.kt:84)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializerSearchUtilKt.getIrSerialTypeInfo(SerializerSearchUtil.kt:63)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.BaseIrGenerator.formEncodeDecodePropertyCall(BaseIrGenerator.kt:255)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.BaseIrGenerator.formEncodeDecodePropertyCall$default(BaseIrGenerator.kt:247)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.BaseIrGenerator.serializeAllProperties(BaseIrGenerator.kt:197)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:345)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$generateWriteSelfMethod$1.invoke(SerializableIrGenerator.kt:291)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.IrBuilderWithPluginContext.addFunctionBody(IrBuilderWithPluginContext.kt:49)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateWriteSelfMethod(SerializableIrGenerator.kt:291)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generateSyntheticMethods(SerializableIrGenerator.kt:372)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator.generate(SerializableIrGenerator.kt:357)
	at org.jetbrains.kotlinx.serialization.compiler.backend.ir.SerializableIrGenerator$Companion.generate(SerializableIrGenerator.kt:383)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializerClassLowering.lower(SerializationLoweringExtension.kt:102)
	... 57 more
[FullError.txt](https://github.com/realm/realm-kotlin/files/10534581/FullError.txt)
```

### PR DESCRIPTION
**Pull request by rorbech**
This PR will change the order of registration of our compiler plugin, so that it is applied after other plugins. This will avoid having other plugins processing our internal `io.realm.kotlin.x`-attributes.

*Reviewing considerations*
I found it hard to put up a test that verifies this across Kotlin versions in the current integration test infrastructure. If we add it in `test-base` it is only verified for Kotlin version of the SDK and if enabling serialization in `examples/kmm-sample` it would only be verified for `Versions.latestKotlin`. I guess the right approach would be to add feature specific projects in `integration-tests/compatibility/<feature>` and trigger those for both `Versions.kotlin` and `Versions.latestKotlin` ... But didn't deem it for this PR!?

Test for current level of `kotlinx.serialization` support. We could do a test in `test-base` to verify the current level of _"out of the box"_ `kotlinx.serialization`-support to catch regressions, but as we don't have full `kotlinx.serialization`-support until #973 and/or #994 I also didn't deem it for this PR. Support at the time of this PR is limited to:
- Kotlin primitive types 
- Bson types
- Object references

Thus not supporting:
- Realm abstract/interface/container types: `RealmInstant`, `RealmUUID`, `MutableRealmInt`, `RealmSet` and `RealmList` 
 
This PR will add *NOT* full `kotlinx.serialization`-support, but will only address the regression mentioned in #1251 for Kotlin 1.8.0 of the _"out of the box"_ working supported field types. See above notes on supported types.

### CODE REVIEW

File: packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt [hunk 1]
```diff
@@ -56,14 +54,22 @@ class Registrar : ComponentRegistrar {
...
-        // Adds RealmObjectInternal properties, rewires accessors and adds static companion
-        // properties and methods
-        IrGenerationExtension.registerExtension(project, RealmModelLoweringExtension())
+        // We load our extensions LAST to avoid exposing our internal attributes to other plugins,
+        // like serialization (issue https://github.com/realm/realm-kotlin/issues/1251).
+        project.extensionArea.run {
+            // Trigger generation of companion objects and addition of the RealmObjectCompanion to it
+            getExtensionPoint(SyntheticResolveExtension.extensionPointName).registerExtension(
+                RealmModelSyntheticCompanionExtension(),
+                LoadingOrder.LAST,
```
Comment (cmelchior) [inline packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt:63]: What happens if multiple plugins define this? I assume behaviour among those is undefined, which I guess is fine. But could users also do this by just reorder the plugins in their build file?

**Review by cmelchior — COMMENTED** [review]
Should we also add a comment in the changelog?

File: packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt (hunk 1 above)
Comment (rorbech) [reply packages/plugin-compiler/src/main/kotlin/io/realm/kotlin/compiler/Registrar.kt:63]: I wasn't able to see a change by reordering the plugins, neither before or after this update. Only other observation that I can chime in with is that I tried I guess it would be best if we could somehow be order agnostic. I tried adding the `@Transient` annotation to the internal attributes from our compiler plugin and that brings compilation past the original error of not being able to find the serializer for `RealmObjectReference` but then compilation fails with 
```
Caused by: java.lang.IllegalStateException: Function has no body: FUN name:write$Self visibility:public modality:FINAL <> (self:com.example.github1252.CityDto, output:kotlinx.serialization.encoding.CompositeEncoder, serialDesc:kotlinx.serialization.descriptors.SerialDescriptor) returnType:kotlin.Unit
```
I fail to see why we should mess up the generated body for that, but maybe it is because we add the supertypes in the lowering instead of fully syntheziced types. And this somehow all goes away if we just load our extensions last, so ... I went with that for now.

**Comment by rorbech** [comment]
> Should we also add a comment in the changelog?

I wouldn't really deem this a bug fix since we don't really have serialization support besides what is coincidentally working out of the box. We also haven't stated the support anywhere so I thought it was better to not mentionen it at all.

**Review by cmelchior — APPROVED** [review]
