### PR TITLE
Fix list indexof, remove and contains

### LINKED ISSUE #1625: Optimize `indexOf` and `contains` for `RealmList`
Most of the `ListOperator` implementations could utilize the C-API `realm_list_find` method to prevent moving all list elements to memory and matching them in Kotlin.

### PR DESCRIPTION
**Pull request by rorbech**
This PR passes arguments to `RealmList`s `indexOf`, `remove` and `contains` to core instead of relying on Kotlin object equality checks. 

Closes #1625 RKOTLIN-995

### CODE REVIEW

File: packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmAnyNestedListNotificationTest.kt [hunk 1]
```diff
@@ -252,4 +255,97 @@ class RealmAnyNestedListNotificationTest : FlowableTests, DeletableEntityNotific
     override fun closeRealmInsideFlowThrows() {
         TODO("Not yet implemented")
     }
+
+    @Test
+    @Ignore // https://github.com/realm/realm-core/issues/7264
```
Comment (clementetb) [inline packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmAnyNestedListNotificationTest.kt:260]: https://github.com/realm/realm-core/issues/7264 has been closed

File: packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmListNotificationsTests.kt [hunk 2]
```diff
@@ -734,6 +737,80 @@ class RealmListNotificationsTests : RealmEntityNotificationTests {
...
+                assertIs<UpdatedList<*>>(it)
+                assertEquals(1, it.list.size)
+                assertEquals("TEST", it.list[0].stringField)
+            }
+
+            listener.cancel()
+        }
+    }
+    @Test
+    @Ignore // https://github.com/realm/realm-core/issues/7264
```
Comment (clementetb) [inline packages/test-base/src/commonTest/kotlin/io/realm/kotlin/test/common/notifications/RealmListNotificationsTests.kt:777]: https://github.com/realm/realm-core/issues/7264 has been closed.

**Review by clementetb — APPROVED** [review]
Looks good to me
