### PR TITLE
Fix list notifications operation on the wrong realm reference

### LINKED ISSUE #827: Crash when collecting RealmObjects
Hello,

I'm using the `0.11.0-SNAPSHOT` version of the SDK.

I'm trying to collect some changes in a RealmList.
It's working when data are removed from the list, but if some items are updated or added, it crashes with this exception:
```
java.lang.RuntimeException: Could not get element at list index 1: RealmCoreException([20]: No object with key '66' in 'class_Thread')
```

As you will see in the logs, the number of items in the list is correct: 1 item the 1st time the collect triggers, 3 the 2nd time.
I'm able to log the 1st item both time, as expected.
But when I try to log the other items, that's when it crashes.

I wrote a small sample to reproduce the situation:

```kotlin
import android.os.Bundle
import android.util.Log
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import io.realm.*
import io.realm.MutableRealm.UpdatePolicy
import io.realm.annotations.PrimaryKey
import kotlinx.coroutines.launch
import java.util.*

class MainActivity : AppCompatActivity() {

    private class Folder : RealmObject {
        @PrimaryKey
        var id: String? = null
        var threads: RealmList<Thread> = realmListOf()
    }

    private class Thread : RealmObject {
        @PrimaryKey
        var id: String? = null
        var subject: String? = null
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val config = RealmConfiguration.Builder(
            setOf(Folder::class, Thread::class)
        ).build()

        val realm = Realm.open(config)

        // Delete everything to have a clean start
        deleteRealmContent(realm)

        // Create folder
        val folder = createFolder(realm)

        // Get Realm folder
        val realmFolder = realm.query<Folder>("${Folder::id.name} == '${folder.id}'").first().find() ?: return

        // Listen to Threads changes
        collectThreads(realmFolder)

        // Populate folder
        addThreadsToFolder(realm, folder)
    }

    private fun deleteRealmContent(realm: Realm) {
        with(realm) {
            val threadsToDelete = query<Thread>().find()
            val foldersToDelete = query<Folder>().find()
            writeBlocking {
                threadsToDelete.mapNotNull(::findLatest).forEach(::delete)
                foldersToDelete.mapNotNull(::findLatest).forEach(::delete)
            }
        }
    }

    private fun createFolder(realm: Realm): Folder {
        val folder = Folder().apply { id = "Folder_1"; threads = getThreads(1) }
        realm.writeBlocking { copyToRealm(folder, UpdatePolicy.ALL) }
        return folder
    }

    private fun collectThreads(folder: Folder) {
        lifecycleScope.launch {
            folder.threads.asFlow().collect { listChange ->
                Log.i("Threads", "Size: ${listChange.list.size}")
                listChange.list.forEachIndexed { index, thread ->
                    Log.d("Threads", "Index: $index - Subject: ${thread.subject}")
                }
            }
        }
    }

    private fun addThreadsToFolder(realm: Realm, folder: Folder) {
        folder.threads = getThreads(3)
        realm.writeBlocking { copyToRealm(folder, UpdatePolicy.ALL) }
    }

    private fun getThreads(nbThreads: Int): RealmList<Thread> {
        val thread1 = Thread().apply { id = "Thread_1"; subject = "Subject of 1st thread_${UUID.randomUUID()}" }
        val thread2 = Thread().apply { id = "Thread_2"; subject = "Subject of 2nd thread_${UUID.randomUUID()}" }
        val thread3 = Thread().apply { id = "Thread_3"; subject = "Subject of 3rd thread_${UUID.randomUUID()}" }
        val thread4 = Thread().apply { id = "Thread_4"; subject = "Subject of 4th thread_${UUID.randomUUID()}" }
        val thread5 = Thread().apply { id = "Thread_5"; subject = "Subject of 5th thread_${UUID.randomUUID()}" }

        return when (nbThreads) {
            1 -> listOf(thread1)
            2 -> listOf(thread1, thread2)
            3 -> listOf(thread1, thread2, thread3)
            4 -> listOf(thread1, thread2, thread3, thread4)
            else -> listOf(thread1, thread2, thread3, thread4, thread5)
        }.toRealmList()
    }
}
```

### PR DESCRIPTION
**Pull request by rorbech**
Closes #827

### CODE REVIEW

File: test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt [hunk 1]
```diff
@@ -293,6 +296,25 @@ class RealmListTests {
         assertEquals(2, realm.query<RealmListContainer>().find().size)
     }
 
+    @Test
+    fun listNotifications() = runBlocking {
+        val container = realm.writeBlocking { copyToRealm(RealmListContainer()) }
+        val collect = async {
+            container.objectListField.asFlow()
+                .takeWhile { it.list.size < 5 }
```
Comment (cmelchior) [inline test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt:304]: This looks wrong? It will take the empty initial list and then complete? Shouldn't this be `it.list.size == 1` ?

**Review by cmelchior — CHANGES_REQUESTED** [review]
Looks good, but we should probably retarget releases + I had a few questions about the test.

File: test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt (hunk 1 above)
Comment (rorbech) [reply test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt:304]: `takeWhile` collects until the condition is no longer met at which time the flow will be completed!? 

So we will keep on adding elements until there are five elements in the list and stop the test. ??

File: packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt [hunk 2]
```diff
@@ -133,13 +134,15 @@ internal class ManagedRealmList<E>(
...
+            val converter: RealmValueConverter<E> = converter<Any>(metadata.clazz, metadata.mediator, frozenRealm) as CompositeConverter<E, *>
+            ManagedRealmList(it, metadata.copy(realm = frozenRealm, converter = converter))
         }
     }
 
     override fun thaw(liveRealm: RealmReference): ManagedRealmList<E>? {
         return RealmInterop.realm_list_resolve_in(nativePointer, liveRealm.dbPointer)?.let {
-            ManagedRealmList(it, metadata.copy(realm = liveRealm))
+            val converter: RealmValueConverter<E> = converter<Any>(metadata.clazz, metadata.mediator, liveRealm) as CompositeConverter<E, *>
+            ManagedRealmList(it, metadata.copy(realm = liveRealm, converter = converter))
```
[the remark this answers is not in the document]
Comment (rorbech) [reply packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmListInternal.kt:145]: Yeah. I have already changed it to an explicit interface method in https://github.com/realm/realm-kotlin/pull/797/files#diff-6ae484901f6301d8cce7b3b571876dbdefc491334d69fe44ec1f77ce69a96acfR212, but since this is a hot-fix I just added it to the existing data class's copy method. We are only copying the metadata when thawing/freezing so think it should be ok for the time being and until #797 is merged.

**Comment by rorbech** [comment]
> Looks good, but we should probably retarget releases + I had a few questions about the test.

I was already doing the fix in `releases`, just forgot to target that. I have tried to put some clarifying comments on the concerns.

File: test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt (hunk 1 above)
Comment (cmelchior) [reply test/base/src/androidTest/kotlin/io/realm/test/shared/RealmListTests.kt:304]: Ah yeah, I was reading the test wrong 👍

**Review by cmelchior — APPROVED** [review]
:shipit:
