### PR TITLE
[RKOTLIN-1114] Fix sync client config not applied

### LINKED ISSUE #1811: Platform networking not working
### How frequently does the bug occur?

Always

### Description

Since 2.0.0 the client sync configuration has not been applied. 

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

_No response_

### Version

2.0.0

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

-- select --

### Platform OS and version(s)

JVM

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

### PR DESCRIPTION
**Pull request by clementetb**
This PR includes the changes from the previous PR https://github.com/realm/realm-kotlin/pull/1801 as it ended up addressing some of the flaky tests from that. 
 
TODOs:
- [x] ~~Depends on https://github.com/realm/realm-kotlin/pull/1801 for green client reset and flx progress listener tests~~ Now includes all changes from #1801 
- [x] Await that https://github.com/realm/realm-core/pull/7891 is merged and bump to an official Core release

Closes #1811

### CODE REVIEW

File: packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt [hunk 1]
```diff
@@ -158,11 +159,12 @@ public class AppConfigurationImpl @OptIn(ExperimentalKBsonSerializerApi::class)
     }
 
     private fun initializeSyncClientConfig(
+        appConfigPointer: RealmAppConfigurationPointer,
         webSocketTransport: WebSocketTransport?,
         sdkInfo: String?,
         applicationInfo: String?
     ): RealmSyncClientConfigurationPointer =
-        RealmInterop.realm_sync_client_config_new()
+        RealmInterop.realm_app_config_get_sync_client_config(appConfigPointer)
```
Comment (nirinchev) [inline packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt:167]: This function appears to be unimplemented and I'm not even sure how it could be implemented considering that `AppConfig::SyncClientConfig` is a simple struct and not a pointer, so getting it would just give us a copy. I've opened https://github.com/realm/realm-core/pull/7792 to discuss how this is intended to be used by consumers.

Comment (rorbech) [reply packages/library-sync/src/commonMain/kotlin/io/realm/kotlin/mongodb/internal/AppConfigurationImpl.kt:167]: https://github.com/realm/realm-core/pull/7792 has been superseded by https://github.com/realm/realm-core/pull/7891 that adds the implementation for `realm_app_config_get_sync_client_config` and is now merged.

File: packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/PlatformNetworkingTests.kt [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+                        uploadRealm.write {
+                            copyToRealm(
+                                SyncObjectWithAllTypes().apply {
+                                    stringField = selector
+                                }
+                            )
+                        }
+                        uploadRealm.syncSession.uploadAllLocalChanges(TIMEOUT)
+                        withTimeout(TIMEOUT) {
+                            realm.query<SyncObjectWithAllTypes>().asFlow().first { it.list.size == 1 }
```
Comment (nhachicha) [inline packages/test-sync/src/jvmTest/kotlin/io/realm/kotlin/test/mongodb/jvm/PlatformNetworkingTests.kt:54]: can we assert the `stringField` is `== selector`

**Review by nhachicha — APPROVED** [review]

**Comment by rorbech** [comment]
Still having issues with some flaky tests. Have gone into experimental mode to try to gather some insights, so pausing review until settled.
