### PR TITLE
Ensure existence of valid transaction on frozen realm references

### LINKED ISSUE #683: Invalid syntax error on seemingly correct query
The following query https://github.com/realm/realm-kotlin/pull/650/commits/65d57fdadc2dcd48d83afcd13a9025a9325f7792#diff-6a88ff735acdb7c19b9ee8237d2aaea90cb18f97a133232f3300e912f945180eL126 failed on CI in the JVM test stage. 

CouIdn't reproduce it locally, so maybe more of an invalid underlying query pointer than an actual syntax error.

```[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-636)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-637)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-638)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-639)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-640)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-641)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-642)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-643)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-644)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-645)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-646)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-647)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-648)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-649)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-650)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-651)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-652)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-653)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-650/7/pipeline#step-360-log-654)io.realm.test.shared.SyncedRealmTests[jvm] > canSync[jvm] FAILED

java.lang.IllegalArgumentException: RealmCoreException [2]: std::exception Invalid syntax in query: [2]: std::exception
        at io.realm.internal.RealmUtilsKt.genericRealmCoreExceptionHandler(RealmUtils.kt:257)
        at io.realm.internal.query.ObjectQuery.tryCatchCoreException(ObjectQuery.kt:172)
        at io.realm.internal.query.ObjectQuery.parseQuery(ObjectQuery.kt:152)
        at io.realm.internal.query.ObjectQuery.<init>(ObjectQuery.kt:52)
        at io.realm.internal.BaseRealmImpl.query(BaseRealmImpl.kt:82)
        at io.realm.test.shared.SyncedRealmTests.canSync(SyncedRealmTests.kt:630)

Caused by:
 io.realm.internal.interop.RealmCoreOtherException: [2]: std::exception
            at app//io.realm.internal.interop.CoreErrorUtils.coreErrorAsThrowable(CoreErrorUtils.kt:26)
            at app//io.realm.internal.interop.realmcJNI.realm_query_parse(Native Method)
            at app//io.realm.internal.interop.realmc.realm_query_parse(realmc.java:600)
            at app//io.realm.internal.interop.RealmInterop.realm_query_parse(RealmInterop.kt:675)
            at app//io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:153)
            at app//io.realm.internal.query.ObjectQuery$parseQuery$1.invoke(ObjectQuery.kt:152)
            at app//io.realm.internal.query.ObjectQuery.tryCatchCoreException(ObjectQuery.kt:162)
            ... 4 more
```

### PR DESCRIPTION
**Pull request by rorbech**
This PR ensures that we have a valid transaction on each frozen realm reference. Failing to have that could cause core to clean up the version and that would render us invalid to query, create objects, etc. from that specific version. 

Closes #683

### CODE REVIEW

File: test/sync/src/androidTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt [hunk 1]
```diff
@@ -125,6 +125,9 @@ class SyncedRealmTests {
 
         val channel = Channel<ResultsChange<ChildPk>>(1)
 
+        // This query has caused trouble on CI
+        assertEquals(0, realm1.query<ChildPk>().find().size, realm1.toString())
```
Comment (cmelchior) [inline test/sync/src/androidTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt:129]: Wow, great catch... that this fails is pretty worrisome though

**Comment by rorbech** [comment]
Seems like it can also fail in the `macos`-test ... https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline

```
[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-865)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-866)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-867)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-868)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-869)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-870)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-871)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-872)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-873)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-874)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-875)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-876)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-877)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-878)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-879)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-880)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-881)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-882)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-883)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-884)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-885)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-886)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-887)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-888)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-889)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-890)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-891)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-892)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-893)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-894)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-895)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-896)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-897)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-898)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-899)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-900)[](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-kotlin/detail/PR-702/2/pipeline#step-238-log-901)io.realm.test.shared.SyncedRealmTests.canSync FAILED
    kotlin.IllegalArgumentException: RealmCoreException [RLM_ERR_OTHER_EXCEPTION]: std::exception Invalid syntax in query: [RLM_ERR_OTHER_EXCEPTION]: std::exception
        at kotlin.Exception#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:25)
        at kotlin.RuntimeException#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:36)
        at kotlin.IllegalArgumentException#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:61)
        at io.realm.internal#genericRealmCoreExceptionHandler(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmUtils.kt:261)
        at io.realm.internal.query.ObjectQuery.tryCatchCoreException#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:175)
        at io.realm.internal.query.ObjectQuery.parseQuery#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:155)
        at io.realm.internal.query.ObjectQuery#<init>(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:55)
        at io.realm.internal.BaseRealmImpl#query(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/BaseRealmImpl.kt:80)
        at io.realm.internal.RealmImpl#query(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmImpl.kt:119)
        at io.realm.test.shared.SyncedRealmTests#canSync(/Users/realm/workspace-realm-kotlin/PR-702/test/sync/src/macosTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt:129)
        at io.realm.test.shared.$SyncedRealmTests$test$0.$canSync$FUNCTION_REFERENCE$61.invoke#internal(/Users/realm/workspace-realm-kotlin/PR-702/test/sync/src/macosTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt:157)
        at io.realm.test.shared.$SyncedRealmTests$test$0.$canSync$FUNCTION_REFERENCE$61.$<bridge-UNNN>invoke(/Users/realm/workspace-realm-kotlin/PR-702/test/sync/src/macosTest/kotlin/io/realm/test/shared/SyncedRealmTests.kt:157)
        at kotlin.native.internal.test.BaseClassSuite.TestCase#run(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestSuite.kt:85)
        at kotlin.native.internal.test.TestRunner.run#internal(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:245)
        at kotlin.native.internal.test.TestRunner.runIteration#internal(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:271)
        at kotlin.native.internal.test.TestRunner#run(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:286)
        at kotlin.native.internal.test#testLauncherEntryPoint(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:30)
        at kotlin.native.internal.test#main(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:34)
        at <global>.Konan_start(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:33)
        at <global>.Init_and_run_start(Unknown Source)
        at <global>.start(Unknown Source)
        at kotlin.Throwable#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:24)
        at kotlin.Exception#<init>(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
        at io.realm.internal.interop.RealmCoreException#<init>(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/Errors.kt:22)
        at io.realm.internal.interop.RealmCoreOtherException#<init>(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/commonMain/kotlin/io/realm/internal/interop/Errors.kt:29)
        at io.realm.internal.interop#coreErrorAsThrowable(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/Errors.kt:26)
        at io.realm.internal.interop.throwOnError#internal(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt)
        at io.realm.internal.interop.checkedPointerResult#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:125)
        at io.realm.internal.interop.CPointerWrapper#<init>(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:131)
        at io.realm.internal.interop.CPointerWrapper#<init>(/Users/realm/workspace-realm-kotlin/PR-702/packages/cinterop/src/darwin/kotlin/io/realm/internal/interop/RealmInterop.kt:139)
        at io.realm.internal.interop.RealmInterop#realm_query_parse(/Users/teamcity1/teamcity_work/6326934d18cfe24e/kotlin/kotlin-native/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt:636)
        at io.realm.internal.query.ObjectQuery.parseQuery$lambda-2#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:156)
        at io.realm.internal.query.ObjectQuery.$parseQuery$lambda-2$FUNCTION_REFERENCE$19.invoke#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:155)
        at io.realm.internal.query.ObjectQuery.tryCatchCoreException#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:165)
        at io.realm.internal.query.ObjectQuery.parseQuery#internal(/Users/realm/workspace-realm-kotlin/PR-702/packages/library-base/src/commonMain/kotlin/io/realm/internal/query/ObjectQuery.kt:155)```

File: packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt [hunk 2]
```diff
@@ -73,7 +73,15 @@ public data class FrozenRealmReference(
...
     override val dbPointer: FrozenRealmPointer,
     override val schemaMetadata: SchemaMetadata = CachedSchemaMetadata(dbPointer),
-) : RealmReference
+) : RealmReference {
+    init {
+        // realm_open/realm_freeze doesn't implicitly create a transaction which can cause the
+        // underlying core version to be cleaned up if the realm is advanced before any objects,
+        // queries, etc. triggers creation of the transaction. Thus, we need to force a transaction
+        // on any realm references to keep the version around for future operations.
+        RealmInterop.realm_begin_read(dbPointer)
```
Comment (nhachicha) [inline packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt:82]: I thought obtaining a Frozen Realm from core will automatically pin the underlying version without the need of starting a read transaction ...

**Review by nhachicha — APPROVED** [review]
Nice catch 👍

File: packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt (hunk 2 above)
Comment (rorbech) [reply packages/library-base/src/commonMain/kotlin/io/realm/internal/RealmReference.kt:82]: Yes, thought that too. It also sounds like core team would agree that this would be the correct approach, but historically some usage patterns have called for not doing it ... and it seems less risky for us to just fix it locally until the approach is revisited in a broader scope.
